version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  backend:
    build:
      context: ../..
      dockerfile: herd_behavior_alerter/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      KAFKA_BROKER_URL: kafka:9092
      # Add environment variables for email/slack if needed
      # SMTP_SERVER: your_smtp_server
      # SMTP_PORT: 587
      # EMAIL_USER: your_email
      # EMAIL_PASSWORD: your_password
      # ALERT_EMAIL_RECIPIENTS: recipient1@example.com,recipient2@example.com
      # SLACK_WEBHOOK_URL: your_slack_webhook_url
    depends_on:
      - kafka

  stream_processor:
    build:
      context: ../..
      dockerfile: herd_behavior_alerter/stream_processor/Dockerfile
    environment:
      KAFKA_BROKER_URL: kafka:9092
      KAFKA_CONSUMER_GROUP: faust-stream-group
    depends_on:
      - kafka

  frontend:
    build:
      context: ../..
      dockerfile: herd_behavior_alerter/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

